# Generated by Django 4.1.7 on 2023-05-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True)),
                (
                    "photo",
                    models.ImageField(default="default_coach", upload_to="coach_pics"),
                ),
                ("description", models.TextField(null=True)),
            ],
            options={
                "verbose_name": "Тренер",
                "verbose_name_plural": "Тренерский состав",
            },
        ),
    ]
