# Generated by Django 4.1.7 on 2023-05-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, null=True, verbose_name="Название"),
                ),
                (
                    "image",
                    models.ImageField(
                        default="default_new",
                        upload_to="news_pics",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "description",
                    models.TimeField(
                        max_length=5000, null=True, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости клуба",
            },
        ),
        migrations.AlterField(
            model_name="coach",
            name="description",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="coach",
            name="name",
            field=models.CharField(max_length=50, null=True, verbose_name="Ф.И.О"),
        ),
        migrations.AlterField(
            model_name="coach",
            name="photo",
            field=models.ImageField(
                default="default_coach", upload_to="coach_pics", verbose_name="Фото"
            ),
        ),
    ]
