# Generated by Django 4.1.7 on 2023-05-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_news_alter_coach_description_alter_coach_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="description",
            field=models.TextField(max_length=5000, null=True, verbose_name="Описание"),
        ),
    ]
