# Generated by Django 4.1.7 on 2023-05-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_news_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sign_for_class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, null=True, verbose_name="Ф.И.О"),
                ),
                ("birthday", models.DateField(null=True, verbose_name="Дата рождения")),
                (
                    "phone_number",
                    models.IntegerField(null=True, verbose_name="Номер телефона"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, null=True, verbose_name="Почта"),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=1000,
                        null=True,
                        verbose_name="Краткая информация о заявителе",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на занятие",
                "verbose_name_plural": "Заявки на занятия",
            },
        ),
    ]
