# Generated by Django 4.1.7 on 2023-05-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_about_school"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about_school",
            options={
                "verbose_name": "Абзац с описанием школы",
                "verbose_name_plural": "Абзацы с описанием школы",
            },
        ),
        migrations.AlterField(
            model_name="about_school",
            name="title",
            field=models.CharField(
                max_length=50,
                null=True,
                verbose_name="Название абзаца о футбольной школе",
            ),
        ),
    ]
