# Generated by Django 4.1.7 on 2023-05-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_trains"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trains",
            options={"verbose_name": "Тренировка", "verbose_name_plural": "Тренировки"},
        ),
        migrations.AddField(
            model_name="trains",
            name="age",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Возраст ребенка"
            ),
        ),
        migrations.AddField(
            model_name="trains",
            name="cost_of_first_train",
            field=models.CharField(
                default="Первая тренировка: бесплатно!",
                max_length=50,
                verbose_name="Стоймость первой тренировки",
            ),
        ),
        migrations.AddField(
            model_name="trains",
            name="duration",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Продолжительность тренировки"
            ),
        ),
        migrations.AddField(
            model_name="trains",
            name="frequency",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Периодичность тренировок"
            ),
        ),
    ]
