# Generated by Django 4.1.7 on 2023-05-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_trains_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, null=True, verbose_name="Ф.И.О"),
                ),
                (
                    "photo",
                    models.ImageField(
                        default="default_student",
                        upload_to="student_pics",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "description",
                    models.TextField(null=True, verbose_name="Описание результатов"),
                ),
            ],
            options={
                "verbose_name": "Ученик",
                "verbose_name_plural": "Ученики",
            },
        ),
    ]
