# Generated by Django 4.1.7 on 2023-05-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery")),
            ],
            options={
                "verbose_name": "Картинка для галереи",
                "verbose_name_plural": "Галерея",
            },
        ),
    ]
