# Generated by Django 4.1.7 on 2023-05-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_gallery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sign_for_class",
            name="birthday",
        ),
        migrations.AlterField(
            model_name="sign_for_class",
            name="description",
            field=models.TextField(
                max_length=1000, null=True, verbose_name="Комментарий"
            ),
        ),
        migrations.AlterField(
            model_name="sign_for_class",
            name="name",
            field=models.CharField(max_length=50, null=True, verbose_name="Имя"),
        ),
    ]
