# Generated by Django 4.1.7 on 2023-06-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_sign_for_class_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sign_for_class",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Номер телефона"
            ),
        ),
    ]
