# Generated by Django 4.1.7 on 2023-06-03 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_rename_phone_number_sign_for_class_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_ages", models.CharField(max_length=20)),
                ("time", models.CharField(max_length=20)),
                ("days", models.CharField(max_length=20)),
                (
                    "coach_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.coach"
                    ),
                ),
            ],
            options={
                "verbose_name": "Расписание",
                "verbose_name_plural": "Расписание занятий",
            },
        ),
    ]
